# Generated by Django 4.0.2 on 2022-03-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_member_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='number',
        ),
    ]
